default_context:
  project_name: 'shopping_cart'
  project_slug: 'shopping_cart'
  domain_main: 'shopping_cart.com'
  domain_staging: 'stag.shopping_cart.com'
  docker_swarm_stack_name_main: 'shopping_cart-com'
  docker_swarm_stack_name_staging: 'stag-shopping_cart-com'
  secret_key: 'db3474a615dff5b68ad9f5013de8c1c0fc475ad219d96753b08ed574c9afd157'
  first_superuser: 'admin@shopping_cart.com'
  first_superuser_password: 'ab95100anc'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.shopping_cart.com", "https://stag.shopping_cart.com", "https://shopping_cart.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.mailgun.org'
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@shopping_cart.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@shopping_cart.com'
  pgadmin_default_user_password: 'ab95100anc'
  traefik_constraint_tag: 'shopping_cart.com'
  traefik_constraint_tag_staging: 'stag.shopping_cart.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:ab95100anc'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
